[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "toolsan"
version = "1.0.5"
authors = [{name = "VLAD", email = "gkkasatik7719@gmail.com"}]
description = """toolsan — это не просто библиотека. Это инструментарий для тех, кто хочет писать чистый, мощный и красивый код на Python. Она рождалась этим летом — в жару, под шум клавиатуры и с мыслью о том, что программирование должно приносить радость.

В toolsan входит всё, что нужно для повседневной разработки:

· Математика — от среднего арифметического до матричного умножения
· Консоль — цветной вывод, анимации, прогресс-бары
· Работа с данными — простая JSON-база данных
· Декораторы — ускорение, отладка, красивое оформление
· Искусственный интеллект — диалог с нейросетью в одну строку

Библиотека создавалась подростком, но с мыслью о взрослых задачах. Она проста на входе, но гибка внутри. toolsan — это твой помощник в коде, который не подведёт."""
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "requests",
    "pymorphy3",
    "pypistats"
]
license = {text = "MIT"}